### ISSUE TITLE
Make addition of `path` field configurable

### ISSUE THREAD

**Issue by ypid-geberit** [logstash-plugins/logstash-input-unix#26]
When using https://github.com/logstash-plugins/logstash-filter-fingerprint for fingerprinting, you need to control all fields to get the same fingerprint/document ID. Consider that during normal operation, Logstash reads inputs from files (file input) but in a recovery scenario the log files get piped (after uncompromising) into Logstash via Unix sockets. For this, no additional field should be added by the unix input.

https://github.com/logstash-plugins/logstash-input-unix/blob/63ac5314f0647a256e1931fe3530b7ae63a591cb/lib/logstash/inputs/unix.rb#L97

**Comment by kares** [comment]
believe this kind of scenario is very usage specific and are best to be handled explicitly in the pipeline config 
e.g. having a `mutate { remove_field => 'path' }` before doing the *fingerprint*-ing. 

in a broader picture having extra fields always configurable would mean a lot of work for all the inputs out there, and often would not make sense to try to force inputs to produce the same event layouts.

**Comment by ypid-geberit** [comment]
After reading this with a few years delay I agree with you, this is very specific. I guess I requested it because of general limitations of Logstash. I have since then reconsidered and replaced Logstash by Vector. So lets close this issue.
